### ISSUE TITLE
新闻列表顺序问题

### ISSUE THREAD

**Issue by MontaneMouse** [edushare/xijingfeedback#10]
1、门户新闻列表循序是按照后台设置的逆序排列的
![image](https://cloud.githubusercontent.com/assets/12946624/8447330/68217778-1fe9-11e5-8fbf-0cd78d0cf6e7.png)
2、门户后台新闻列表应该按照更新时间排序，最新更新的排在最前面
![qq 20150701120412](https://cloud.githubusercontent.com/assets/12946624/8447342/bf390b66-1fe9-11e5-81e4-86727d9197c0.png)

**Comment by edushare** [comment]
fixed
