### ISSUE TITLE
活动未能在门户显示出来

### ISSUE THREAD

**Issue by MontaneMouse** [edushare/xijingfeedback#11]
![qq 20150701121222](https://cloud.githubusercontent.com/assets/12946624/8447379/2f8b89ac-1fea-11e5-8afe-e60590935636.png)
![qq 20150701121256](https://cloud.githubusercontent.com/assets/12946624/8447386/47640f7c-1fea-11e5-839a-84e1a31d55c8.png)

**Comment by edushare** [comment]
这个不是问题，不显示是因为你活动设定的时间已经过去了。
