### ISSUE TITLE
课程章节父子节点的问题

### ISSUE THREAD

**Issue by MontaneMouse** [edushare/xijingfeedback#16]
![qq 20150701151557](https://cloud.githubusercontent.com/assets/12946624/8449416/da909162-2003-11e5-90e1-d78e9771520c.png)

如上图所示：推荐阅读是一个父目录，本身不需要添加内容，但课程资源平台的设置里面，要求必须添加内容

**Comment by edushare** [comment]
如果不想添加内容，就用HTML格式，写个简单介绍，一般每个章，在子章节的前面也有一段介绍性文字的。

**Comment by MontaneMouse** [comment]
这个不一定有
