### ISSUE TITLE
严重Bug，课程章节列表混乱，无法调整

### ISSUE THREAD

**Issue by MontaneMouse** [edushare/xijingfeedback#38]
![qq 20150812100541](https://cloud.githubusercontent.com/assets/12946624/9215196/bf64132c-40d9-11e5-88e5-8c2f0bb73657.png)

**Comment by edushare** [comment]
课程列表右上角有解锁功能，解锁后，章节间可以拖动调整。目前的拖动确实有些问题，已经安排人员解决。
