### ISSUE TITLE
门户首页样式问题

### ISSUE THREAD

**Issue by MontaneMouse** [edushare/xijingfeedback#5]
![qq 20150701111949](https://cloud.githubusercontent.com/assets/12946624/8446873/daaaad70-1fe2-11e5-9418-557ad65c2a99.png)

传统的使用习惯是在顶端大幻灯片直接链接到具体的内容去查看即可，因此首页不需要再在下边显示幻灯片要表达的详细内容，建议从首页门户去掉

**Comment by edushare** [comment]
UI 需求需要进一步澄清
