### ISSUE TITLE
课程信息设置编辑问题

### ISSUE THREAD

**Issue by MontaneMouse** [edushare/xijingfeedback#8]
![image](https://cloud.githubusercontent.com/assets/12946624/8447000/803b2548-1fe4-11e5-962c-49d37ffb824b.png)
1、建议将设置，信息，编辑者三个选项卡合并，统称为课程基本信息，在这个选项卡里面做具体的设置；
2、编辑者实际上是共建教师，添加共建教师最好提供搜索功能，根据搜索结果进行添加，目前按照老师的工号进行添加，太复杂，不好操作；

**Comment by edushare** [comment]
除了搜索功能意外，其它已改
