### ISSUE TITLE
在门户和课程资源平台需要分别登陆

### ISSUE THREAD

**Issue by MontaneMouse** [edushare/xijingfeedback#9]
1、在平台登陆后，还需要在门户登陆下，才能进入门户个人课程空间浏览个人课程信息；
2、在门户登陆后，教师要求，点击自己建设的课程可以直接跳转到课程进行建设，或者也可以进行浏览学习

**Comment by edushare** [comment]
第一条，无法重现
第二条，目前就是这样设计，进入管理空间，一定要单独登陆。
